// Heuristic detection IT/EN per source_market_type.
// Estratta da /api/admin/market-translations (route deprecated 2026-04-24 in E3).
// Usata da Market Normalization per flaggare markets EN non-mappati (red flag reale:
// player vede stringa inglese grezza quando il market non è canonicalizzato).

const ITALIAN_PATTERNS: RegExp[] = [
  /^1X2(\s|$)/, /^U\/O(\s|$)/, /^GG\/NG/, /^DC(\s|$)/, /^P\/D$/,
  /^Pari\/Dispari/, /^Risultato Esatto/, /^Handicap/, /^Draw No Bet/,
  /^Vincente/, /^Testa a Testa/, /^Rete Inviolata/, /^Vincente A 0/,
  /^Parziale\/Finale/, /^Tempo Con/, /^Tempi Supplementari/,
  /^Passaggio Turno/, /^Prima Squadra/, /^Marcatore/, /^Primo Marcatore/,
  /^Ultimo Marcatore/, /^Tripletta/, /^Doppietta/, /^Multigol/,
  /^Somma Gol/, /^Set Betting/, /^Numero Esatto/, /^T\/T/,
  /^Tiebreak/, /^Gol In Entrambi/, /^Vince .+ Tempo/,
  /^Ribaltone/, /^Autorete/, /^Gol Nei Primi/, /^Squadra .+ Segna/,
  /^1X2 Corner/, /^U\/O Corner/, /^DC Corner/, /^Fascia Corner/,
  /^Gara A \d+ Corner/, /^Handicap Corner/, /^Handicap Asiatico/,
  /^1X2 Handicap/, /^1X2 \d+° Tempo/, /^U\/O \d+° Tempo/,
  /^DC \d+° Tempo/, /^GG\/NG \d+° Tempo/, /^Pari\/Dispari \d+° Tempo/,
  /^Risultato Esatto \d+° Tempo/, /^Multigol \d+° Tempo/,
  /^U\/O Casa/, /^U\/O Ospite/, /^U\/O Incl/, /^U\/O Games/,
  /^U\/O Giochi/, /^Pari\/Dispari Casa/, /^Pari\/Dispari Ospite/,
  /^Pari\/Dispari Games/, /^Pari\/Dispari Set/, /^Pari\/Dispari Incl/,
  /^1X2 \+ /, /^DC \+ /, /^GG\/NG \+ /, /^Combo/,
  /^1X2 \d+ Minuti/,
  /\d°\s*Periodo/, /\d°\s*Quarto/,
  /^Handicap \d°\s*Tempo/,
  /^Handicap Punti/,
  /^Metodo Primo Gol/, /^Tempo Primo Gol/, /^Rigore/,
  /^Numero Esatto Gol/, /^Squadra Segna Gol/,
  /^Quarto Con Più Punti/, /^Falli Totali/, /^Rinvii Dal Fondo/,
  /^Entrambi Vincono Un Set/, /^G\d Vince Almeno/,
  /^Handicap Set/, /^U\/O Set/, /^U\/O Games G\d/,
  /^Vincente Set \d+/, /^Gara A \d+ Games/,
  /^Deuce\s/, /^In Vantaggio Dopo/,
  /^Risultato Esatto \(Best Of/,
  /^Vincente Mappa/, /^U\/O Mappe/, /^Vincente Incontro \+ Vincente Mappa/,
  /^Power Play/, /Gol PP/, /^Risultato Gol PP/,
  /Tiri In Porta/, /Tiri Totali/, /Tiri Di Testa/,
  /Tiri (Sinistro|Destro)/, /Passaggi Completati/,
  /Contrasti Difensivi/, /\bAssist$/, /\bFalli$/,
  /\bParate$/, /\bRespinte$/, /\bFuorigioco$/, /\bCross$/,
  /Cartellini/,
  /^Primo Corner/, /^Espulsione/, /^Marcatore 2\+/,
  /^Primo Marcatore (Casa|Ospite)/, /^Marcatore (Piede|Di Testa|Fuori)/,
  /^Gara A \d+ Gol/, /^Mappa \d+:/, /^1X2 Mappa/,
  /^Handicap Runs/, /^U\/O Runs/, /^Handicap Punti/,
  /^Vince Entrambi/, /^Entrambi Tempi/,
  /^Vincente (Casa|Ospite)/, /^Squadra Segna Gol/,
  /^U\/O G\d/, /^Handicap Set/,
  /^Segna/, /^Esito/, /^Totale/, /^Entrambe/,
  /^Gol\s/, /^Corner\s/, /^Più\s/, /^Piú\s/,
  /^Doppia\s/, /^Autogol/, /^Fornisce/, /^Supplementari/,
  /^Almeno/, /^Cartellino\s/, /^Riceve\s/, /^Prende\s/,
  /^Corsa\s/, /^Prossimo\s/, /^Mappa\s\d/, /^\d°\s*Set/,
  /^Va\s+in/, /^Mappe\s/, /^Punti/, /^Margine\s/,
  /^Ogni\s/, /^1x2\s/,
  /^Calci/, /^Angoli/, /^Angolo/, /^Fuorigioco/,
  /^Rimbalzi/, /^Fa\s/, /^Tiri\s/, /^Assist\s/,
  /^Set\s\d/, /^Risultato\s/, /^Primo\s/,
  /vince almeno/, /vince e entrambe/, /vince senza subire/,
  /segna un gol/, /prende un cartellino/, /Scommessa nulla/,
  /subire gol/, /segna un gol su calcio/,
  /^Tempo\s/, /\d°\s*Gioco/, /^Numero totale/, /^Stoppate/,
  /^Passaggio del/, /^Palle perse/, /^Palle recuperate/,
  /^Miglior/, /^Maggior/, /^Pareggio/, /^Scommessa/,
  /^Effettua/, /^Prossima/, /^Mete\s/, /^Resto\s/,
  /^Registra/, /^Run\s/, /^Prima a/, /^Primo\/a/,
  /Tie-break al/, /^\d°\s*tempo/,
];

const ITALIAN_PATTERNS_CI = ITALIAN_PATTERNS.map((p) => new RegExp(p.source, "i"));

export function isItalian(marketType: string): boolean {
  return ITALIAN_PATTERNS_CI.some((p) => p.test(marketType));
}
