-- ═══════════════════════════════════════════════════
-- Migration 013: Team Aliases table for Flashscore matching
-- Stores canonical→alias pairs to improve fuzzy matching.
-- Static aliases are in lib/team-aliases.ts; this table
-- holds user-added overrides from the admin UI.
-- ═══════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS team_aliases (
  id SERIAL PRIMARY KEY,
  canonical TEXT NOT NULL,
  alias TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(canonical, alias)
);

-- Seed with common aliases that are hard to match programmatically
INSERT INTO team_aliases (canonical, alias) VALUES
  -- Italian clubs
  ('inter', 'internazionale'),
  ('inter', 'inter milano'),
  ('inter', 'inter milan'),
  ('milan', 'ac milan'),
  ('juventus', 'juve'),
  ('roma', 'as roma'),
  ('lazio', 'ss lazio'),
  ('napoli', 'ssc napoli'),
  ('verona', 'hellas verona'),
  ('torino', 'torino fc'),
  ('bologna', 'bologna fc'),
  ('fiorentina', 'acf fiorentina'),
  ('atalanta', 'atalanta bergamo'),
  ('genoa', 'genoa cfc'),
  ('sampdoria', 'uc sampdoria'),
  ('como', 'como 1907'),
  -- National teams IT→EN
  ('japan', 'giappone'),
  ('germany', 'germania'),
  ('usa', 'stati uniti'),
  ('england', 'inghilterra'),
  ('france', 'francia'),
  ('spain', 'spagna'),
  ('portugal', 'portogallo'),
  ('netherlands', 'olanda'),
  ('belgium', 'belgio'),
  ('sweden', 'svezia'),
  ('norway', 'norvegia'),
  ('denmark', 'danimarca'),
  ('finland', 'finlandia'),
  ('switzerland', 'svizzera'),
  ('greece', 'grecia'),
  ('turkey', 'turchia'),
  ('poland', 'polonia'),
  ('czech republic', 'repubblica ceca'),
  ('hungary', 'ungheria'),
  ('croatia', 'croazia'),
  ('serbia', 'serbia'),
  ('ukraine', 'ucraina'),
  ('wales', 'galles'),
  ('scotland', 'scozia'),
  ('ireland', 'irlanda'),
  ('iceland', 'islanda'),
  ('south korea', 'corea del sud'),
  ('china', 'cina'),
  ('brazil', 'brasile'),
  ('mexico', 'messico'),
  ('ivory coast', 'costa d''avorio'),
  ('cameroon', 'camerun'),
  ('egypt', 'egitto'),
  ('morocco', 'marocco'),
  ('saudi arabia', 'arabia saudita'),
  ('south africa', 'sudafrica'),
  ('new zealand', 'nuova zelanda'),
  -- International clubs
  ('man utd', 'manchester united'),
  ('man city', 'manchester city'),
  ('tottenham', 'spurs'),
  ('wolves', 'wolverhampton'),
  ('barcelona', 'barca'),
  ('atletico madrid', 'atl madrid'),
  ('bayern', 'bayern munich'),
  ('bayern', 'bayern munchen'),
  ('dortmund', 'borussia dortmund'),
  ('leverkusen', 'bayer leverkusen'),
  ('leipzig', 'rb leipzig'),
  ('psg', 'paris saint-germain'),
  ('marsiglia', 'marseille'),
  ('lione', 'lyon'),
  ('monaco', 'as monaco'),
  ('ajax', 'ajax amsterdam'),
  ('psv', 'psv eindhoven'),
  ('benfica', 'sl benfica'),
  ('porto', 'fc porto'),
  ('sporting', 'sporting cp'),
  ('sporting', 'sporting lisbona'),
  ('dinamo zagabria', 'dinamo zagreb'),
  ('stella rossa', 'red star belgrade'),
  ('slavia praga', 'slavia prague'),
  ('sparta praga', 'sparta prague'),
  ('cska mosca', 'cska moscow'),
  ('copenhagen', 'copenaghen'),
  ('copenhagen', 'kobenhavn')
ON CONFLICT DO NOTHING;
