-- 069_wave_19_kambi_opta_esports_corners.sql
-- Wave 19 — 95% coverage push continuation.
-- Scope:
--   Kambi Opta player props (scorer, assist, cards, shots)
--   22bet esports (frags, first blood, nashor, inhibitor, round OE)
--   22bet tennis (point score per serve, serve hold with score, race to games)
--   22bet tournament (highest/lowest scoring match, most/least scoring team)
--   22bet corner intervals (Calcio D'angolo Dal Minuto Al Minuto)
--   22bet scraper-bugged markets (market_type canonicalize only)

INSERT INTO canonical_markets (canonical_key, base_key, period, canonical_name_it, has_line, outcomes) VALUES
  -- ═══ Kambi Opta player props ═══
  ('player_scores_goals_ft', 'player_scores_goals', 'ft', 'Giocatore Segna Gol (N+)', true,
   '[{"key":"grid","name_it":"Player × Sì/No"}]'::jsonb),
  ('player_scores_header_ft', 'player_scores_header', 'ft', 'Giocatore Segna Di Testa', true,
   '[{"key":"grid","name_it":"Player × Sì/No"}]'::jsonb),
  ('player_scores_outside_ft', 'player_scores_outside', 'ft', 'Giocatore Segna Da Fuori Area', true,
   '[{"key":"grid","name_it":"Player × Sì/No"}]'::jsonb),
  ('player_assists_ft', 'player_assists', 'ft', 'Giocatore Fornisce Assist', true,
   '[{"key":"grid","name_it":"Player × Sì/No"}]'::jsonb),
  ('player_scores_or_assists_ft', 'player_scores_or_assists', 'ft', 'Giocatore Segna o Assist', true,
   '[{"key":"grid","name_it":"Player × Sì/No"}]'::jsonb),
  ('player_booked_ft', 'player_booked', 'ft', 'Giocatore Riceve Cartellino', true,
   '[{"key":"grid","name_it":"Player × Sì/No"}]'::jsonb),
  ('player_red_card_ft', 'player_red_card', 'ft', 'Giocatore Cartellino Rosso', true,
   '[{"key":"grid","name_it":"Player × Sì/No"}]'::jsonb),
  ('player_shots_on_target_ft', 'player_shots_on_target', 'ft', 'Giocatore Tiri In Porta', true,
   '[{"key":"grid","name_it":"Player × O/U"}]'::jsonb),
  ('total_shots_on_target_ft', 'total_shots_on_target', 'ft', 'Totale Tiri In Porta', true,
   '[{"key":"over","name_it":"Over"},{"key":"under","name_it":"Under"}]'::jsonb),
  ('more_shots_on_target_ft', 'more_shots_on_target', 'ft', 'Più Tiri In Porta', false,
   '[{"key":"home","name_it":"1"},{"key":"away","name_it":"2"}]'::jsonb),
  ('woodwork_hit_ft', 'woodwork_hit', 'ft', 'Palo o Traversa Colpita', false,
   '[{"key":"yes","name_it":"Sì"},{"key":"no","name_it":"No"}]'::jsonb),

  -- ═══ 22bet esports ═══
  ('first_blood_ft', 'first_blood', 'ft', 'Primo Sangue', false,
   '[{"key":"home","name_it":"1"},{"key":"away","name_it":"2"},{"key":"none","name_it":"Nessuno"}]'::jsonb),
  ('first_blood_1h', 'first_blood', '1h', 'Primo Sangue 1° Mappa', false,
   '[{"key":"home","name_it":"1"},{"key":"away","name_it":"2"},{"key":"none","name_it":"Nessuno"}]'::jsonb),
  ('first_blood_2h', 'first_blood', '2h', 'Primo Sangue 2° Mappa', false,
   '[{"key":"home","name_it":"1"},{"key":"away","name_it":"2"},{"key":"none","name_it":"Nessuno"}]'::jsonb),
  ('first_blood_3h', 'first_blood', '3h', 'Primo Sangue 3° Mappa', false,
   '[{"key":"home","name_it":"1"},{"key":"away","name_it":"2"},{"key":"none","name_it":"Nessuno"}]'::jsonb),
  ('nashor_ft', 'nashor', 'ft', 'Chi Batterà Nashor', true,
   '[{"key":"grid","name_it":"Nashor #N"}]'::jsonb),
  ('nashor_1h', 'nashor', '1h', 'Chi Batterà Nashor 1° Mappa', true,
   '[{"key":"grid","name_it":"Nashor #N"}]'::jsonb),
  ('nashor_2h', 'nashor', '2h', 'Chi Batterà Nashor 2° Mappa', true,
   '[{"key":"grid","name_it":"Nashor #N"}]'::jsonb),
  ('inhibitor_destroyed_ft', 'inhibitor_destroyed', 'ft', 'Totale Inhibitor Distrutti', true,
   '[{"key":"over","name_it":"Over"},{"key":"under","name_it":"Under"}]'::jsonb),
  ('inhibitor_destroyed_1h', 'inhibitor_destroyed', '1h', 'Inhibitor Distrutti 1° Mappa', true,
   '[{"key":"over","name_it":"Over"},{"key":"under","name_it":"Under"}]'::jsonb),
  ('inhibitor_destroyed_2h', 'inhibitor_destroyed', '2h', 'Inhibitor Distrutti 2° Mappa', true,
   '[{"key":"over","name_it":"Over"},{"key":"under","name_it":"Under"}]'::jsonb),
  ('frag_race_ft', 'frag_race', 'ft', 'Sfida Al Frag', true,
   '[{"key":"home","name_it":"1"},{"key":"away","name_it":"2"}]'::jsonb),
  ('frag_race_1h', 'frag_race', '1h', 'Sfida Al Frag 1° Mappa', true,
   '[{"key":"home","name_it":"1"},{"key":"away","name_it":"2"}]'::jsonb),
  ('frag_race_2h', 'frag_race', '2h', 'Sfida Al Frag 2° Mappa', true,
   '[{"key":"home","name_it":"1"},{"key":"away","name_it":"2"}]'::jsonb),
  ('frag_total_oe_ft', 'frag_total_oe', 'ft', 'Totale Frag Pari/Dispari', false,
   '[{"key":"even","name_it":"Pari"},{"key":"odd","name_it":"Dispari"}]'::jsonb),
  ('frag_total_oe_1h', 'frag_total_oe', '1h', 'Frag Pari/Dispari 1° Mappa', false,
   '[{"key":"even","name_it":"Pari"},{"key":"odd","name_it":"Dispari"}]'::jsonb),
  ('frag_total_oe_2h', 'frag_total_oe', '2h', 'Frag Pari/Dispari 2° Mappa', false,
   '[{"key":"even","name_it":"Pari"},{"key":"odd","name_it":"Dispari"}]'::jsonb),
  ('round_total_oe_ft', 'round_total_oe', 'ft', 'Totale Round Pari/Dispari', false,
   '[{"key":"even","name_it":"Pari"},{"key":"odd","name_it":"Dispari"}]'::jsonb),
  ('round_total_oe_1h', 'round_total_oe', '1h', 'Round Pari/Dispari 1° Mappa', false,
   '[{"key":"even","name_it":"Pari"},{"key":"odd","name_it":"Dispari"}]'::jsonb),
  ('round_total_oe_2h', 'round_total_oe', '2h', 'Round Pari/Dispari 2° Mappa', false,
   '[{"key":"even","name_it":"Pari"},{"key":"odd","name_it":"Dispari"}]'::jsonb),

  -- ═══ 22bet tennis extended ═══
  ('point_score_first_serve_1h', 'point_score_first_serve', '1h', 'Punteggio Primo Servizio 1° Set', true,
   '[{"key":"grid","name_it":"Score"}]'::jsonb),
  ('point_score_first_serve_2h', 'point_score_first_serve', '2h', 'Punteggio Primo Servizio 2° Set', true,
   '[{"key":"grid","name_it":"Score"}]'::jsonb),
  ('serve_hold_with_score_1h', 'serve_hold_with_score', '1h', 'Vince Primo Turno Con Punteggio 1° Set', false,
   '[{"key":"grid","name_it":"Score per player"}]'::jsonb),
  ('serve_hold_with_score_2h', 'serve_hold_with_score', '2h', 'Vince Primo Turno Con Punteggio 2° Set', false,
   '[{"key":"grid","name_it":"Score per player"}]'::jsonb),
  ('games_race_1h', 'games_race', '1h', 'Sfida Al Games 1° Set', true,
   '[{"key":"home","name_it":"1"},{"key":"away","name_it":"2"}]'::jsonb),
  ('games_race_2h', 'games_race', '2h', 'Sfida Al Games 2° Set', true,
   '[{"key":"home","name_it":"1"},{"key":"away","name_it":"2"}]'::jsonb),

  -- ═══ 22bet tournament-level ═══
  ('tournament_most_scoring_match_ft', 'tournament_most_scoring_match', 'ft', 'Partita Con Più Marcature (tournament)', true,
   '[{"key":"over","name_it":"Over"},{"key":"under","name_it":"Under"}]'::jsonb),
  ('tournament_least_scoring_match_ft', 'tournament_least_scoring_match', 'ft', 'Partita Con Meno Marcature (tournament)', true,
   '[{"key":"over","name_it":"Over"},{"key":"under","name_it":"Under"}]'::jsonb),
  ('tournament_most_scoring_team_ft', 'tournament_most_scoring_team', 'ft', 'Squadra Con Più Marcature (tournament)', true,
   '[{"key":"over","name_it":"Over"},{"key":"under","name_it":"Under"}]'::jsonb),
  ('tournament_least_scoring_team_ft', 'tournament_least_scoring_team', 'ft', 'Squadra Con Meno Marcature (tournament)', true,
   '[{"key":"over","name_it":"Over"},{"key":"under","name_it":"Under"}]'::jsonb),
  ('tournament_highest_away_score_ft', 'tournament_highest_away_score', 'ft', 'Punteggio Più Alto Trasferta (tournament)', true,
   '[{"key":"over","name_it":"Over"},{"key":"under","name_it":"Under"}]'::jsonb),
  ('tournament_matches_overunder_ft', 'tournament_matches_overunder', 'ft', 'Totale Partite O/U (tournament)', true,
   '[{"key":"over","name_it":"Over"},{"key":"under","name_it":"Under"}]'::jsonb),

  -- ═══ 22bet corner minute interval ═══
  ('corner_interval_ft', 'corner_interval', 'ft', 'Calcio D''angolo Intervallo', false,
   '[{"key":"grid","name_it":"Min range"}]'::jsonb),
  ('team1_corner_interval_ft', 'team1_corner_interval', 'ft', 'Calcio D''angolo Squadra 1 Intervallo', false,
   '[{"key":"grid","name_it":"Min range"}]'::jsonb),
  ('team2_corner_interval_ft', 'team2_corner_interval', 'ft', 'Calcio D''angolo Squadra 2 Intervallo', false,
   '[{"key":"grid","name_it":"Min range"}]'::jsonb),

  -- ═══ Scraper-bug markets (market_type canonicalize, outcomes bugged) ═══
  ('first_goal_time_ft', 'first_goal_time', 'ft', 'Momento Primo Goal', false,
   '[{"key":"grid","name_it":"Fascia Min"}]'::jsonb),
  ('team_half_first_goal_ft', 'team_half_first_goal', 'ft', 'Squadra Segna Primo Goal in Tempo', false,
   '[{"key":"grid","name_it":"Team × Half"}]'::jsonb),
  ('super_handicap_ft', 'super_handicap', 'ft', 'SuperHandicap', false,
   '[{"key":"grid","name_it":"Asian H × Rimborso"}]'::jsonb),
  ('super_handicap_1h', 'super_handicap', '1h', 'SuperHandicap 1° Tempo', false,
   '[{"key":"grid","name_it":"Asian H × Rimborso"}]'::jsonb),
  ('super_handicap_2h', 'super_handicap', '2h', 'SuperHandicap 2° Tempo', false,
   '[{"key":"grid","name_it":"Asian H × Rimborso"}]'::jsonb),
  ('super_total_ft', 'super_total', 'ft', 'SuperTotale', false,
   '[{"key":"grid","name_it":"Asian O/U × Rimborso"}]'::jsonb),
  ('super_total_1h', 'super_total', '1h', 'SuperTotale 1° Tempo', false,
   '[{"key":"grid","name_it":"Asian O/U × Rimborso"}]'::jsonb),
  ('super_total_2h', 'super_total', '2h', 'SuperTotale 2° Tempo', false,
   '[{"key":"grid","name_it":"Asian O/U × Rimborso"}]'::jsonb),
  ('exact_total_sets_ft', 'exact_total_sets', 'ft', 'Numero Esatto Totale di Set', false,
   '[{"key":"grid","name_it":"N"}]'::jsonb),
  ('exact_total_ft', 'exact_total', 'ft', 'Numero Esatto', false,
   '[{"key":"grid","name_it":"N"}]'::jsonb)
ON CONFLICT (canonical_key) DO NOTHING;
